CelsiusNetwork/celsius-app

.gitignore, app/components/organisms/ReferralReceivedModal/ReferralReceivedModal.js, app/components/screens/TransactionDetails/TransactionDetailsSections.js, app/services/branch-service.js, app/utils/analytics.js, package.json, set-env.js
=> Google Branch Expo Pizdarije

app/components/screens/CameraScreen/CameraScreen.js
KYC quality of pictures - compression issue fix
=> CN-2838: KYC picture quality compression fixes

app/components/atoms/InterestRateInfo/InterestRateInfo.js, app/components/graphs/PieProgressBar/PieProgressBar.js, app/components/molecules/InterestRateInfoTable/InterestRateInfoTable.js, app/components/organisms/BecameCelMemberModal/BecameCelMemberModal.js, app/components/organisms/TodayInterestRatesModal/TodayInterestRatesModal.js, app/components/screens/CoinDetails/CoinDetails.js, app/components/screens/Deposit/Deposit.js, app/components/screens/LoyaltyProgram/LoyaltyProgram.js, app/components/screens/Profile/Profile.js, app/components/screens/TransactionDetails/TransactionDetails.js, app/components/screens/TransactionDetails/TransactionDetailsSections.js, app/components/screens/WalletInterest/WalletInterest.js, app/components/screens/WalletSettings/WalletSettings.js, app/navigator/flows/profileFlow.js, app/redux/app/appActions.js, app/redux/generalData/generalDataReducer.js, app/utils/formatter.js, app/utils/transactions-util.js
https://mvpworkshop.atlassian.net/browse/CN-2855
Enable all hidden CEL utility features:
* Show Interest rates for CEL token
* Enable `Earn interest in CEL` switch
* Fix TransactionsDetails for Interest transactions
* Enable LoyaltyInfo screen
=> CN-2855: Enabling CEL Utility

app/components/screens/CoinDetails/CoinDetails.js, app/redux/app/appActions.js, app/redux/generalData/generalDataReducer.js
=> CN 3329 refresh rate fix

app/components/organisms/PrepayDollarInterestModal/PrepayDollarInterestModal.js, app/components/screens/ChoosePrepaymentMethod/ChoosePrepaymentMethod.js, app/components/screens/LoanPrepaymentPeriod/LoanPrepaymentPeriod.js, app/components/screens/PaymentCel/PaymentCel.js, app/components/screens/WiringBankInformation/WiringBankInformation.js, app/components/screens/WiringBankInformation/WiringBankInformation.styles.js, app/navigator/flows/borrowFlow.js
=> CN-3556:Wire payment setup flow

app/components/screens/TermsOfUse/TermsOfUse.js
=> CN-3539 remove accept and contact buttons

features/referrals.claim-referral-link.feature, features/referrals.enter-promo-code.feature, features/referrals.enter-referral-code.feature, features/referrals.get-reward.feature, features/referrals.share-individual-referral.feature
=> CN-3557 Referral happy scenarios

app/components/screens/BorrowBankAccount/BorrowBankAccount.js, app/mock-data/loans.mock.js, app/redux/loans/loansActions.js, app/services/loans-service.js, dev-settings.json
=> CN-3611: dev-settings.json added

app/App.js
=> CN-3663: Fix initial session

app/components/atoms/ContactRow/ContactRow.styles.js, app/components/graphs/GraphContainer/GraphContainer.js, app/components/molecules/Message/Message.js, app/components/molecules/Message/Message.styles.js, app/components/organisms/MyCelInterestTab/MyCelInterestTab.styles.js, app/components/organisms/MyCelLoansTab/MyCelLoansTab.styles.js, app/components/organisms/MyCelOverivewTab/MyCelOverivewTab.styles.js, app/components/screens/ApiAuthorization/ApiAuthorization.js, app/components/screens/Appearance/Appearance.js, app/components/screens/Community/Community.js, app/components/screens/Community/Community.styles.js, app/components/screens/TermsOfUse/TermsOfUse.js, app/components/screens/TermsOfUse/TermsOfUse.styles.js, app/components/screens/TransactionDetails/TransactionDetails.js, app/components/screens/TransactionDetails/TransactionDetailsSections.js
=> CN-3736 UI/UX workshop improvements

docs/contributing.md
=> [DRAFT] CONTRIBUTING.md

app/components/screens/RegisterSetPin/RegisterSetPin.js
=> CN-3675 hide back button on set pin screen

app/components/atoms/EmptyState/EmptyState.js, app/components/organisms/LoanApplicationSuccessModal/LoanApplicationSuccessModal.js, app/components/organisms/LoanOverviewCard/LoanOverviewCard.js, app/components/screens/BorrowLanding/BorrowLanding.js, app/components/screens/LoanRequestDetails/LoanRequestDetails.js, app/redux/loans/loansActions.js, app/utils/empty-state-util.js
=> CN-3001 loan bugs

app/components/screens/Profile/Profile.js, app/components/screens/Settings/Settings.js, app/components/screens/Welcome/Welcome.js, app/utils/analytics.js, app/utils/api-util.js, app/utils/app-util.js, app/utils/logger-util.js
=> CN-3808 App version number shown in the app

app/components/molecules/InterestCard/InterestCard.js, app/components/screens/CoinDetails/CoinDetails.js
=> CN-38178: Interest card spacing fixes

app/components/molecules/InterestCard/InterestCard.js, app/components/screens/KYCProfileDetails/KYCProfileDetails.js, app/components/screens/RegisterInitial/RegisterInitial.js
=> CN 3855 CN 3883 CN 3843 ma bug report v4

app/components/atoms/BalanceView/BalanceView.js, app/components/atoms/BalanceView/BalanceView.styles.js, app/components/atoms/InfoBox/InfoBox.js, app/components/screens/CelPayEnterAmount/CelPayEnterAmount.js, app/components/screens/WithdrawConfirmAddress/WithdrawConfirmAddress.js, app/components/screens/WithdrawConfirmAddress/WithdrawConfirmAddress.styles.js, app/components/screens/WithdrawCreateAddress/WithdrawCreateAddress.js, app/components/screens/WithdrawCreateAddress/WithdrawCreateAddress.styles.js, app/components/screens/WithdrawEnterAmount/WithdrawEnterAmount.js, app/components/screens/WithdrawEnterAmount/WithdrawEnterAmount.styles.js
=> CN-3182- CN-3806 Bug fixes

app/components/atoms/CelInput/CelInput.js
=> CN-3863, CN-3913 Handling error messages

app/redux/app/appActions.js
=> CN-3892 loading app timeout

app/components/screens/WithdrawConfirmAddress/WithdrawConfirmAddress.js, app/components/screens/WithdrawCreateAddress/WithdrawCreateAddress.js
=> CN-3904 Keyboard dismisses on pressing done

app/components/screens/BorrowEnterAmount/BorrowEnterAmount.js, app/components/screens/ConfirmYourLoan/ConfirmYourLoan.js, app/components/screens/TransactionDetails/TransactionDetails.js, app/components/screens/TransactionDetails/TransactionDetailsSections.js
=> CN-3979: Loan bugs

app/redux/celPay/celPayActions.js, app/redux/loans/loansActions.js, app/redux/transactions/transactionsActions.js, app/redux/user/authActions.js, app/redux/user/kycActions.js, app/redux/user/thirdPartyActions.js, app/utils/app-util.js, app/utils/appsflyer-util.js
=> CN-4016 appsflyer integration test

app/constants/UI.js
=> CN-4074 loyalty bonus value

app/components/molecules/KYCandPromotionsTrigger/KYCandPromotionsTrigger.js, app/components/screens/LoanTermsOfUse/LoanTermsOfUse.js
=> CN-4081 tou numeration

app/redux/loans/loansActions.js
=> CN-4161 prepayment flow change on pin

app/components/screens/LoanSettings/LoanSettings.js
=> CN-4191: Remove principal settings

android/app/src/main/AndroidManifest.xml
=> CN-4203: Android 7 crash

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, app/utils/expo-storage.js, package.json
=> CN-4226: Log-in Ooops msg

app/components/screens/BorrowLanding/BorrowLanding.js
=> CN-4231 Remove hasEnoughForLoan check

app/components/atoms/Spinner/Spinner.js, app/components/layouts/RegularLayout/RegularLayout.js, app/components/layouts/RegularLayout/RegularLayout.styles.js, app/components/screens/WalletLanding/WalletLanding.js
=> CN-4143 Pull to refresh on WalletLanding

app/constants/DATA.js
=> CN-4341 Added urls from backoffice for ZEC and BCH that work

app/components/molecules/SocialSecurityNumber/SocialSecurityNumber.styles.js
=> CN-4350 numbers visible

app/components/atoms/CelModalButton/CelModalButton.js, app/components/modals/BecomeCelMemberModal/BecomeCelMemberModal.js, app/components/modals/BecomeCelMemberModal/BecomeCelMemberModal.styles.js, app/components/modals/CancelLoanModal/CancelLoanModal.js, app/components/modals/CancelLoanModal/CancelLoanModal.styles.js, app/components/modals/InfoModalNew/InfoModal.js, app/components/modals/Modal.stories.js
=> CN-4264, CN-4274: BecomeCelMemberModal and CancelLoanModal

app/components/modals/ApiKeyRevokeModal/ApiKeyRevokeModal.js, app/components/modals/ApiKeyRevokeModal/ApiKeyRevokeModal.styles.js, app/components/modals/InfoModalNew/InfoModal.js, app/components/modals/LoseMembershipModal/LoseMembershipModal.js, app/components/modals/LoseMembershipModal/LoseMembershipModal.styles.js, app/components/modals/LoseTierModal/LoseTierModal.js, app/components/modals/LoseTierModal/LoseTierModal.styles.js, app/components/modals/MemoIdModal/MemoIdModal.js, app/components/modals/MemoIdModal/MemoIdModal.styles.js, app/components/modals/Modal.stories.js, app/components/modals/RemoveAuthAppModal/RemoveAuthAppModal.js, app/components/modals/RemoveAuthAppModal/RemoveAuthAppModal.styles.js, app/components/screens/ApiAuthorization/ApiAuthorization.js, app/components/screens/SecuritySettings/SecuritySettings.js, plops/modal/info.js.txt
=> CN 4394 CN 4395 CN 4396 CN 4397 CN 4399 simple info modals pt1

app/components/atoms/ReferralTrigger/ReferralTrigger.js, app/components/modals/InterestDueModal/InterestDueModal.js, app/components/molecules/Banner/Banner.js, app/components/organisms/LoanOverviewCard/LoanOverviewCard.js, app/components/screens/BorrowLanding/BorrowLanding.js, app/utils/user-behavior-util.js
```
What does this implement/fix? Explain your changes.
Are there any scripts that need running (eg. yarn install)?
Are there any edge cases that need checking?
Are there any specific test instructions?
```
=> CN-4468, CN-4431: test smaller stuff for v4.1.0

app/components/organisms/CelStats/CelStats.js
```
What does this implement/fix? Explain your changes.
Are there any scripts that need running (eg. yarn install)?
Are there any edge cases that need checking?
Are there any specific test instructions?
```
=> CN-4335 added explanation text to Community page

app/redux/celPay/celPayActions.js
=> CN-4549 celpay friend fix

app/components/molecules/CelNumpad/CelNumpad.js, app/components/screens/BorrowEnterAmount/BorrowEnterAmount.js, app/components/screens/CelPayEnterAmount/CelPayEnterAmount.js, app/components/screens/VerifyProfile/VerifyProfile.js, app/components/screens/WithdrawEnterAmount/WithdrawEnterAmount.js, app/redux/ui/uiActions.js
=> CN-4550 Keypad is showing up

app/components/molecules/SendCelPayLinkCard/SendCelPayLinkCard.js, app/components/screens/CelPayChooseFriend/CelPayChooseFriend.js, app/components/screens/CelPayEnterAmount/CelPayEnterAmount.js, app/components/screens/CelPayLanding/CelPayLanding.js, app/components/screens/CelPayMessage/CelPayMessage.js, app/constants/UI.js, app/redux/celPay/celPayActions.js, app/redux/contacts/contactsActions.js, app/redux/contacts/contactsReducer.js, app/redux/nav/navReducer.js, app/redux/transfers/transfersActions.js, app/services/contacts-service.js, app/utils/analytics/cel-pay-analytics.js, app/utils/mixpanel-analytics.js, app/utils/user-behavior-util.js
=> CN-4583: Add CelPay analytics

app/components/screens/Home/Home.js, app/utils/api-util.js
=> CN-4732 flagged hideBack after login

app/components/atoms/CoinSwitch/CoinSwitch.js, app/components/screens/GetCoinsEnterAmount/GetCoinsEnterAmount.js, app/redux/simplex/simplexActions.js
=> CN-4782: Fixing simplex display amounts

app/components/molecules/RateInfoCard/RateInfoCard.js
=> CN-4802 added condition isUSResident

app/components/molecules/RateInfoCard/RateInfoCard.js, app/redux/generalData/generalDataReducer.js, app/redux/user/loyaltyActions.js, app/utils/interest-util.js
=> CN-4814, CN-4821, CN-4823: interest rate display fixes

app/components/atoms/CoinSwitch/CoinSwitch.js
=> CN-4866 disabled toggle keypad when no coin

app/components/atoms/ReferralTrigger/ReferralTrigger.js, app/components/modals/GetCoinsInfoModal/GetCoinsInfoModal.js, app/components/molecules/Banner/Banner.stories.js
=> CN-4829 CN-4799 Copy changes

app/App.js, app/utils/branch-util.js
=> CN-4836: disabling mandatory code push of the app

app/redux/app/appActions.js
=> CN-4904: fixing interest loyalty display

app/components/screens/GetCoinsEnterAmount/GetCoinsEnterAmount.js
=> CN-4872: fiat amount validation

app/components/atoms/CelInput/CelInputPassword.js, app/utils/password-util.js, package.json
=> CN-4946 added password-meter library and basic strength meter logic

app/components/molecules/TransactionsHistory/TransactionsHistory.js, app/redux/transactions/transactionsReducer.js, app/utils/transaction-map-util.js, app/utils/transactions-filter-util.js
=> CN-4930 Split transactions util into two utils

app/components/atoms/HodlBanner/HodlBanner.js, app/components/atoms/TransactionRow/TransactionRow.js, app/components/atoms/TransactionRow/TransactionRow.styles.js, app/components/atoms/TxInfoSection/TxInfoSection.js, app/components/atoms/TxInfoSection/TxInfoSection.styles.js, app/components/molecules/TransactionsHistory/TransactionsHistory.js, app/components/screens/TransactionsIntersection/TransactionsIntersection.js, app/components/screens/TransactionsIntersection/TransactionsIntersection.styles.js, app/navigator/Navigator.js, app/utils/crypto-util.js, app/utils/transaction-map-util.js
=> Cn 4952 intersection for all transaction screens

app/components/layouts/RegularLayout/RegularLayout.js, app/components/screens/BorrowLanding/BorrowLanding.js, app/components/screens/CelPayLanding/CelPayLanding.js
=> CN-5007, CN-4991: pull to refresh

app/components/screens/Login/Login.js, app/components/screens/RegisterInitial/RegisterInitial.js, app/utils/recaptcha-util.js
=> CN-5009: Added error handling to reCaptcha and some refactor

android/app/src/main/AndroidManifest.xml, app/utils/push-notifications-util.js
=> CN-5022: Double notfications fix

app/components/atoms/CelInput/CelInput.js, app/components/atoms/CelInput/CelInputPassword.js, app/components/atoms/PassMeterTooltip/PassMeterTooltip.styles.js, app/components/atoms/PassStrengthMeter/PassStrengthMeter.styles.js, app/components/screens/ChangePassword/ChangePassword.js, app/components/screens/RegisterInitial/RegisterInitial.js
removed round borders above pass meter line
added copy to change pass screen
=> CN-5023: pass meter polishing

app/components/atoms/CelInput/CelInputText.js
=> CN-4982: Added trim to email field

app/utils/app-util.js, app/utils/mixpanel-analytics/general-analytics.js, app/utils/uxcam-util.js
=> CN-5049 connect ux cam to mixpanel

app/components/screens/CoinDetails/CoinDetails.js
=> CN-5203 hide deposit button if not compliant

app/components/atoms/ContactRow/ContactRow.js, app/components/modals/ConfirmCelPayModal/ConfirmCelPayModal.js, app/components/molecules/CoinPicker/CoinPicker.styles.js, app/components/organisms/CelHeading/CelHeading.js, app/components/screens/CelPayChooseFriend/CelPayChooseFriend.js, app/components/screens/TransactionDetailsCelPay/TransactionDetailsCelPay.js, app/components/screens/TransactionDetailsDeposits/TransactionDetailsDeposits.js, app/components/screens/TransactionDetailsInterest/TransactionDetailsInterest.js, app/components/screens/TransactionDetailsLoans/TransactionDetailsLoans.js, app/components/screens/TransactionDetailsRewards/TransactionDetailsRewards.js, app/components/screens/TransactionDetailsWithdraw/TransactionDetailsWithdraw.js, app/components/screens/TransactionsIntersection/TransactionsIntersection.js, app/redux/transfers/transfersActions.js
=> CN-5198, CN-5184, CN-5185: celpay bugs

app/components/atoms/CelModalButton/CelModalButton.js, app/components/screens/VerifyProfile/VerifyProfile.js
=> CN-5226, CN-5229: layout fixes

app/components/screens/BorrowBankAccount/BorrowBankAccount.js, app/components/screens/ConfirmYourLoan/ConfirmYourLoan.js
=> Rename account_holder_name to bank_account_holder_name

app/components/atoms/MissingInfoCard/MissingInfoCard.js
=> CN-5353: Missing address popup, text adjustment

app/components/layouts/RegularLayout/RegularLayout.js, app/components/layouts/RegularLayout/RegularLayout.styles.js, app/components/organisms/CelHeading/CelHeading.js, app/utils/api-util.js, app/utils/mixpanel-util.js
=> CN-5464: JS not convertible into dynamic hell

app/components/molecules/CoinListCard/CoinListCard.js
=> CN-5680 apr into apY

app/components/modals/GetCoinsConfirmModal/GetCoinsConfirmModal.js, app/components/screens/VerifyProfile/VerifyProfile.js, app/utils/logger-util.js
=> CN-5463 undefined route bug

app/components/screens/Welcome/Welcome.js, app/redux/user/userProfileActions.js, app/redux/userAuth/authActions.js
=> CN-5396: Auto logged out message

app/components/modals/MemoIdModal/MemoIdModal.js, app/components/screens/Deposit/Deposit.js
=> CN-5694 deposit modal for eos memo

app/redux/userAuth/authActions.js, app/redux/userSecurity/userSecurityActions.js
=> CN-5808: Call BE when user logs out regularly from the app

app/components/atoms/SecurityStrengthMeter/SecurityStrengthMeter.js, app/components/molecules/MultiInfoCardButton/MultiInfoCardButton.js, app/components/molecules/MultiInfoCardButton/MultiInfoCardButton.styles.js, app/components/organisms/CelHeading/CelHeading.js, app/components/organisms/CheckWithdrawalAddressesCard/CheckWithdrawalAddressesCard.js, app/components/organisms/CheckWithdrawalAddressesCard/CheckWithdrawalAddressesCard.styles.js, app/components/screens/Deposit/Deposit.js, app/components/screens/GetCoinsTransactionDetails/GetCoinsTransactionDetails.js, app/components/screens/WithdrawAddressOverview/WithdrawAddressOverview.js, app/redux/userAuth/authActions.js
=> CN-5814: Late May 2020 Release Fixes

app/components/molecules/CoinGridCard/CoinGridCard.styles.js, app/components/screens/BalanceHistory/BalanceHistory.js, app/components/screens/CameraScreen/CameraScreen.js, app/components/screens/ConfirmCamera/ConfirmCamera.js, app/components/screens/LoanTermsOfUse/LoanTermsOfUse.js, app/components/screens/WalletInterest/WalletInterest.js, app/components/screens/WalletLanding/WalletLanding.js, app/utils/animations-util.js
=> CN-5901 CN-5902 CN-5903 Fix back button on camera - Wrap Coin Cards - Fixed Amount showing on Header

app/components/atoms/NoWithdrawalAddressCard/NoWithdrawalAddressCard.js, app/components/atoms/NoWithdrawalAddressCard/NoWithdrawalAddressCard.styles.js, app/components/atoms/SecurityStrengthMeter/SecurityStrengthMeter.js, app/components/atoms/SecurityStrengthMeter/SecurityStrengthMeter.styles.js, app/components/atoms/WithdrawalAddressCard/WithdrawalAddressCard.js, app/components/atoms/WithdrawalAddressCard/WithdrawalAddressCard.styles.js, app/components/molecules/ToggleInfoCard/ToggleInfoCard.styles.js, app/components/screens/SecurityFixNow/SecurityFixNow.js, app/components/screens/SecurityOverview/SecurityOverview.js, app/components/screens/WithdrawNewAddressSetup/WithdrawNewAddressSetup.js
=> CN-5915: Security screens - UI fixes

app/components/screens/BorrowEnterAmount/BorrowEnterAmount.js, app/components/screens/BorrowLanding/BorrowLanding.js
=> CN-5952 Added BigNumber

app/components/screens/LoginLanding/LoginLanding.js, app/components/screens/Welcome/Welcome.js, app/redux/userAuth/authActions.js, app/utils/api-util.js
=> CN-5626: auto logout

app/components/screens/Home/Home.js, app/utils/api-util.js
=> CN-6148: Create pin ask fix

app/components/screens/WithdrawCreateAddress/WithdrawCreateAddress.js, app/components/screens/WithdrawEnterAmount/WithdrawEnterAmount.js, app/redux/wallet/walletActions.js
=> CN-6513 Withdrawal address flow changed

app/components/modals/RegisterPromoCodeModal/RegisterPromoCodeModal.js, app/components/modals/RegisterPromoCodeModal/RegisterPromoCodeModal.styles.js
=> CN-5747: Color fixed

app/components/organisms/CelHeading/CelHeading.js, app/components/organisms/WalletDetailsCard/WalletDetailsCard.js, app/components/screens/GetCoinsGem/GetCoinsGem.js
=> CN-5995: Beta testing bugs

app/components/screens/ActivateSixDigitPin/ActivateSixDigitPin.js, app/components/screens/ActivateSixDigitPin/ActivateSixDigitPin.styles.js, app/navigator/Navigator.js
=> CN-6161: Created ActivateSixDigitPin screen

app/components/modals/GetCoinsConfirmModal/GetCoinsConfirmModal.js, app/components/screens/BorrowCalculatorScreen/BorrowCalculatorScreen.js, app/components/screens/GetCoinsGem/GetCoinsGem.js, app/components/screens/GetCoinsGem/GetCoinsGem.styles.js, app/utils/api-util.js
=> CN-5990: fixing bugs from comment 2, 4, 6, 7

app/components/modals/GetCoinsInfoModal/GetCoinsInfoModal.js, app/utils/api-util.js
=> CN-6404, CN-6348: bug fixes/copy changes

app/components/atoms/HorizontalSlider/HorizontalSlider.js, app/components/graphs/CircularProgressBar/CircularProgressBar.js, app/components/graphs/CircularProgressBar/CircularProgressBar.styles.js, app/components/layouts/RegularLayout/RegularLayout.js, app/components/organisms/BorrowCalculator/BorrowCalculator.js, app/components/organisms/BorrowCalculator/BorrowCalculator.styles.js, app/components/organisms/CelHeading/CelHeading.js, app/components/organisms/LoanOverviewCard/LoanOverviewCard.styles.js, app/components/screens/BorrowCalculatorScreen/BorrowCalculatorScreen.styles.js, app/components/screens/BorrowEnterAmount/BorrowEnterAmount.stories.js, app/components/screens/BorrowLanding/BorrowLanding.js, app/components/screens/BorrowLanding/BorrowLanding.stories.js, app/components/screens/Screens.stories.js
=> CN-6388: BorrowLanding and BorrowEnterAmount stories

app/components/molecules/CollateralCoinCard/CollateralCoinCard.styles.js, app/components/screens/BorrowCollateral/BorrowCollateral.js, app/components/screens/BorrowCollateral/BorrowCollateral.stories.js, app/components/screens/Screens.stories.js, app/components/screens/Support/Support.js, app/components/screens/Support/Support.stories.js
=> CN-6584: Create stories and reskin BorrowCollateral screen

app/components/screens/BorrowLoanOption/BorrowLoanOption.js, app/redux/generalData/generalDataActions.js, app/redux/loans/loansReducer.js
=> CN-6677 Cant create a loan

app/components/screens/ActivateSixDigitPin/ActivateSixDigitPin.js, app/components/screens/ChangePin/ChangePin.js, app/components/screens/SixDigitPinExplanation/SixDigitPinExplanation.js, app/components/screens/VerifyProfile/VerifyProfile.js, app/constants/DATA.js, app/redux/user/userDataActions.js, app/redux/userSecurity/userSecurityActions.js, app/utils/api-util.js
=> CN-6410: Six digit pin flow fixes

app/components/screens/CelPayChooseFriend/CelPayChooseFriend.stories.js, app/components/screens/Screens.stories.js
=> CN-6610: Create stories and reskin CelPayChooseFriend screen

app/components/screens/TwoFactorSettings/TwoFactorSettings.js, app/redux/app/appActions.js
=> CN-6344: Added TwoFactorSettings screen to later verification

app/utils/api-util.js
=> CN-6875 fixing app version

app/components/screens/SelectCoin/SelectCoin.js, app/components/screens/SelectCountry/SelectCountry.js, app/components/screens/SelectState/SelectState.js, app/redux/kyc/kycActions.js, app/redux/user/userReducer.js
=> CN-6883: Fixing kyc bugs

app/components/modals/TransactionFilterModal/TransactionFilterModal.js, app/components/molecules/DeepLinkController/DeepLinkController.js
=> CN-6817: Deep link handler - little improvements.

app/components/screens/CameraScreen/CameraScreen.js
=> CN-6874, CN-6881: fixing camera crashing issues

app/components/screens/WithdrawCreateAddress/WithdrawCreateAddress.js, app/components/screens/WithdrawCreateAddress/WithdrawCreateAddress.styles.js, app/components/screens/WithdrawNewAddressSetup/WithdrawNewAddressSetup.js, app/redux/wallet/walletActions.js
=> CN-6891: navigating back on wrong tag

app/components/modals/ConfirmPrepaymentModal/ConfirmPrepaymentModal.js, app/components/modals/InfoModalNew/InfoModal.js, app/components/modals/LoanAlertsModals/LoanAlertsPayoutPrincipalModal/LoanAlertsPayoutPrincipalModal.js, app/components/modals/LoanApplicationSuccessModal/LoanApplicationSuccessModal.js, app/components/organisms/TierCard/TierCard.js, app/components/screens/ChoosePaymentMethod/ChoosePaymentMethod.js, app/components/screens/LoanSettings/LoanSettings.js
=> CN-6944 modal for setting up automatic

app/utils/api-util.js
=> CN-6767: fixing 426 oooops errors

app/components/screens/CelPayEnterAmount/CelPayEnterAmount.js
=> CN-6950: celpay fixing copy

app/components/modals/RegisterPromoCodeModal/RegisterPromoCodeModal.js
=> CN-6639: Updated modal and added error handling

app/components/modals/ConfirmPrepaymentModal/ConfirmPrepaymentModal.js, app/components/molecules/LoanInterestCard/LoanInterestCard.js, app/components/screens/BorrowLoanTerm/BorrowLoanTerm.js
=> CN-6690 fix numbers in loan application flow

app/components/atoms/CelInput/CelInput.styles.js, app/components/atoms/CelModalButton/CelModalButton.styles.js, app/components/molecules/Banner/Banner.js, app/components/molecules/Banner/Banner.styles.js, app/components/screens/InterestPaymentSettings/InterestPaymentSettings.js
=> CN-6928: Dark mode fixes

app/components/screens/TransactionsIntersection/TransactionsIntersection.js
=> CN-6347: celpay transaction oops error

plops/component/component.styles.js.txt, plops/screen/screenGen.js, plops/screen/stories.js.txt
=> CN-6958: upgrade plops

app/components/screens/VerifyProfile/VerifyProfile.js, app/redux/app/appActions.js
=> CN-7077, CN-7195: Increased wakeup period and 2fa dots fix

app/components/modals/LoanAlertsModals/LoanAlertsModalWrapper.js, app/components/modals/LoanAlertsModals/LoanAlertsPayoutPrincipalModal/LoanAlertsPayoutPrincipalModal.js, app/components/modals/LoanApplicationSuccessModal/LoanApplicationSuccessModal.js, app/components/modals/PrincipalAlertModal/PrincipalAlertModal.js, app/components/modals/PrincipalAlertModal/PrincipalAlertModal.styles.js, app/components/molecules/LoanCard/LoanCard.js, app/components/molecules/LtvCard/LtvCard.js, app/components/molecules/PaymentCard/PaymentCard.js, app/components/organisms/LoanOverviewCard/LoanOverviewCard.js, app/components/screens/Deposit/Deposit.js, app/components/screens/SingleMarginCallScreen/SingleMarginCallScreen.js, app/components/screens/TransactionDetailsLoans/TransactionDetailsLoans.js, app/redux/loans/loansActions.js, app/utils/loanPayment-util.js
=> CN-7176 Adding principal alert conditions

app/components/atoms/PaymentListItem/PaymentListItem.js, app/components/organisms/TierCard/TierCard.js, app/components/screens/TransactionDetailsLoans/TransactionDetailsLoans.js, app/utils/transaction-map-util.js
=> CN-6997 Loan payment flow UI fixes

app/components/atoms/DepositAddressSwitchCard/DepositAddressSwitchCard.js, app/components/atoms/DepositAddressSwitchCard/DepositAddressSwitchCard.stories.js, app/components/atoms/DepositAddressSwitchCard/DepositAddressSwitchCard.styles.js, app/components/screens/Deposit/Deposit.js, app/redux/wallet/walletActions.js
=> CN-7197: adding segwit bitcoin addresses

app/App.js, app/components/molecules/DeepLinkController/DeepLinkController.js, app/redux/campaign/campaignActions.js, app/redux/deepLink/deepLinkActions.js, app/utils/app-util.js
=> CN-7077: Deep link fix when update is available

app/components/molecules/PinTooltip/PinTooltip.js
=> CN-7175: Hidden dots problem

app/components/atoms/InterestRateInfo/InterestRateInfo.js, app/components/molecules/RateInfoCard/RateInfoCard.js, app/components/screens/WalletLanding/WalletLanding.js
=> CN-6856 Correct interest apy presentation and copy changes

app/components/screens/ConfirmCamera/ConfirmCamera.js, app/components/screens/KYCCheckPhotos/KYCCheckPhotos.js, app/components/screens/KYCVerifyIdentity/KYCVerifyIdentity.js
=> CN-7263: OnfidoSDK testing and bug fixes

app/components/atoms/InterestRateInfo/InterestRateInfo.js, app/components/molecules/CoinGridCard/CoinGridCard.js, app/components/molecules/CoinListCard/CoinListCard.js, app/components/molecules/InterestCard/InterestCard.js, app/components/screens/CoinDetails/CoinDetails.js, app/utils/interest-util.js
=> CN-7308 interest not showing properly

app/components/molecules/ComingSoonCoins/ComingSoonCoins.js, app/components/molecules/ComingSoonCoins/ComingSoonCoins.styles.js, app/constants/DATA.js
=> CN-7206, CN-7096: small improvements

app/components/modals/GetCoinsInfoModal/GetCoinsInfoModal.js, app/components/organisms/FabMenu/FabMenu.js, app/components/organisms/FabMenuAnimated/FabMenuAnimated.js
=> CN-7262: Copy changes

app/components/atoms/CelInput/CelInput.js, app/components/atoms/CelInput/CelInputText.js, app/components/atoms/CelText/CelText.js, app/components/atoms/TransactionRow/TransactionRow.js, app/components/modals/ApiKeySuccessModal/ApiKeySuccessModal.js, app/components/modals/RegisterPromoCodeModal/RegisterPromoCodeModal.js, app/components/molecules/CoinGridCard/CoinGridCard.js, app/components/molecules/CoinListCard/CoinListCard.js, app/components/molecules/Counter/Counter.js, app/components/molecules/SocialSecurityNumber/SocialSecurityNumber.js, app/components/organisms/WalletDetailsCard/WalletDetailsCard.js, app/components/screens/CellphoneEnter/CellphoneEnter.js, app/components/screens/CoinDetails/CoinDetails.js, app/components/screens/Deposit/Deposit.js, app/components/screens/KYCTaxpayer/KYCTaxpayer.js, app/components/screens/Login/Login.js, app/components/screens/PersonalInformation/PersonalInformation.js, app/components/screens/Profile/Profile.js, app/components/screens/WalletInterest/WalletInterest.js, app/utils/uxcam-util.js
=> CN-5048: Prepare which fields to hide in the App

app/components/screens/Home/Home.js, app/components/screens/LoadingScreen/LoadingScreen.js, app/components/screens/WalletLanding/WalletLanding.js
=> CN-7401: Fixing wallet loading

app/components/modals/DepositInfoModal/DepositInfoModal.js, app/components/modals/IntroduceNewThemeModal/IntroduceNewThemeModal.js, app/components/molecules/LoanTrigger/LoanTrigger.js, app/components/organisms/BorrowCalculator/BorrowCalculator.js, app/components/organisms/CommunityDashboard/CommunityDashboard.js, app/components/organisms/MyCelInterestTab/MyCelInterestTab.js, app/components/screens/Appearance/Appearance.js, app/components/screens/BorrowCalculatorScreen/BorrowCalculatorScreen.js, app/components/screens/Community/Community.js, app/components/screens/InterestRates/InterestRates.js, app/components/screens/KYCTaxpayer/KYCTaxpayer.js
=> CN-7397: kristen's feedback

app/components/atoms/CelInput/CelInput.styles.js, app/components/atoms/CelInput/CelInputPassword.js, app/components/atoms/DepositAddressSwitchCard/DepositAddressSwitchCard.js, app/components/atoms/Spinner/Spinner.js, app/components/atoms/TxAddressSection/TxAddressSection.js, app/components/modals/RegisterPromoCodeModal/RegisterPromoCodeModal.js, app/components/molecules/CollateralCoinCard/CollateralCoinCard.js, app/components/organisms/CommunityDashboard/CommunityDashboard.js, app/components/organisms/LoanOverviewCard/LoanOverviewCard.js, app/components/screens/CoinDetails/CoinDetails.js, app/components/screens/LoanPrepaymentPeriod/LoanPrepaymentPeriod.js, app/components/screens/LoanTermsOfUse/LoanTermsOfUse.js, app/components/screens/TransactionDetailsInterest/TransactionDetailsInterest.js, app/components/screens/TransactionDetailsWithdraw/TransactionDetailsWithdraw.js, app/components/screens/TransactionsIntersection/TransactionsIntersection.js, app/components/screens/VerifyProfile/VerifyProfile.js
=> CN-6767 release polishes

app/App.js, app/utils/app-util.js
=> CN-7403: Refresh token mech improved

app/components/modals/RegisterPromoCodeModal/RegisterPromoCodeModal.js, app/redux/campaign/campaignActions.js, app/redux/campaign/campaignReducer.js, app/services/campaigns-service.js
=> CN-7463: Put old promo codes on 4.5 app ver

app/components/screens/GetCoinsEnterAmount/GetCoinsEnterAmount.js
=> CN-7429: Fixing buy coins enter amount

app/App.js, app/components/screens/Home/Home.js, app/utils/app-util.js
=> CN-7547: 6 digit pin issue and double login fix

app/components/modals/RegisterPromoCodeModal/RegisterPromoCodeModal.js, app/redux/campaign/campaignActions.js, app/redux/campaign/campaignReducer.js, app/services/campaigns-service.js
=> CN-7465: New promo code flow integrated to 4.5

app/components/modals/RegisterPromoCodeModal/RegisterPromoCodeModal.js, app/redux/campaign/campaignActions.js, app/redux/campaign/campaignReducer.js, app/services/campaigns-service.js
=> CN-7297: New promo codes from 4.5 to 4.4

app/constants/SCREENS.js
=> CN-7646: Fixing typo

app/components/screens/TransactionDetailsCelPay/TransactionDetailsCelPay.js, app/components/screens/TransactionDetailsDeposits/TransactionDetailsDeposits.js, app/components/screens/TransactionDetailsGeneral/TransactionDetailsGeneral.js, app/components/screens/TransactionDetailsInterest/TransactionDetailsInterest.js, app/components/screens/TransactionDetailsLoans/TransactionDetailsLoans.js, app/components/screens/TransactionDetailsRewards/TransactionDetailsRewards.js, app/components/screens/TransactionDetailsWithdraw/TransactionDetailsWithdraw.js
=> CN-7412: Wrong transaction times displayed in the app

app/components/modals/ConfirmPaymentModal/ConfirmPaymentModal.js, app/components/modals/ConfirmPrepaymentModal/ConfirmPrepaymentModal.js, app/components/molecules/PaymentCard/PaymentCard.js, app/components/organisms/LoanOverviewCard/LoanOverviewCard.js, app/components/organisms/TierCard/TierCard.js, app/components/organisms/TierCard/TierCard.styles.js, app/components/screens/LoanRequestDetails/LoanRequestDetails.js, app/components/screens/TransactionDetailsLoans/TransactionDetailsLoans.js, app/utils/loanPayment-util.js
=> CN-7602: Loan flow improvements 

app/components/modals/BiometricsAuthenticationModal/BiometricsAuthenticationModal.js, app/components/modals/BiometricsNotRecognizedModal/BiometricsNotRecognizedModal.js, app/components/molecules/Banner/Banner.js, app/components/molecules/BiometricsTrigger/BiometricsTrigger.js, app/components/screens/BiometricAuthentication/BiometricAuthentication.js, app/components/screens/SecurityFixNow/SecurityFixNow.js, app/components/screens/SecurityOverview/SecurityOverview.js, app/components/screens/SecuritySettings/SecuritySettings.js, app/components/screens/VerifyProfile/VerifyProfile.js, app/constants/Svgs/CommonSvgs.js, app/constants/UI.js, app/services/biometrics-service.js, app/utils/biometrics-util.js
=> CN-7737: Biometrics UI fixes and feature improvements

app/components/screens/BiometricAuthentication/BiometricAuthentication.js, app/components/screens/BiometricAuthentication/BiometricAuthentication.stories.js, app/components/screens/Screens.stories.js
=> CN-7654: Added Storybook for BiometricAuthentication.js

app/components/organisms/CommunityDashboard/CommunityDashboard.js
=> CN-CM0001: Community Dashboard - Fix default Total Earned.

app/components/modals/ReferralReceivedModal/ReferralReceivedModal.js
=> CN-7994: Referral modal personal info removed

.github/workflows/pipeline.yml, .github/workflows/test.yml
=> CN-8190: Create CI pipeline

app/components/molecules/PaymentCard/PaymentCard.js, app/components/screens/InterestPaymentOverviewScreen/InterestPaymentOverviewScreen.js, app/components/screens/MarginCallOverviewScreen/MarginCallOverviewScreen.js
=> CN-8197 after paying interest user is asked to pay it again

app/components/organisms/BorrowCalculator/BorrowCalculator.js, app/components/screens/BorrowCalculatorScreen/BorrowCalculatorScreen.js
=> CN-7893: borrow calculator coin picker

app/components/modals/InterestDueModal/InterestDueModal.js
=> CN-8269 wallet landing bug

app/components/screens/HODLViewCode/HODLViewCode.js
=> CN-8208: Hide HODL code

app/components/atoms/TxBasicSection/TxBasicSection.js, app/components/screens/GetCoinsEnterAmount/GetCoinsEnterAmount.js, app/components/screens/HODLViewCode/HODLViewCode.js, app/components/screens/TransactionDetailsLoans/TransactionDetailsLoans.js
=> CN-8215: Buy coins amount hidden from UXCam

app/components/atoms/TxBasicSection/TxBasicSection.js, app/components/screens/HODLViewCode/HODLViewCode.js, app/components/screens/Simplex/SimplexScreen.js, app/components/screens/TransactionDetailsLoans/TransactionDetailsLoans.js
=> CN-8217: Hide Credit Card details from UXCam

app/components/atoms/AccountActivityLog/AccountActivityLog.js, app/components/atoms/LoginDevicesLog/LoginDevicesLog.js, app/components/atoms/TxBasicSection/TxBasicSection.js, app/components/screens/HODLViewCode/HODLViewCode.js, app/components/screens/TransactionDetailsLoans/TransactionDetailsLoans.js
=> CN-8213: Hide user actions from UXCam

app/components/atoms/WithdrawalAddressCard/WithdrawalAddressCard.js
=> CN-8209: Hide withdrawal addresses from recording

app/components/organisms/CelHeading/CelHeading.js
=> CN-8206: Hide total balance from recording

app/redux/userAuth/authActions.js, app/redux/userAuth/thirdPartyActions.js, app/utils/uxcam-util.js
=> CN-8210: Social Login fix - UXCam

app/utils/cel-utility-util.js
=> CN-8288, CN-8348: cel withdrawal issue

app/components/modals/InterestDueModal/InterestDueModal.js, app/utils/loan-util.js
=> CN-8270 app crashes

app/components/modals/ConfirmWithdrawalDetailsModal/ConfirmWithdrawalDetailsModal.js, app/components/modals/ConfirmWithdrawalDetailsModal/ConfirmWithdrawalDetailsModal.styles.js, app/components/organisms/WalletDetailsCard/WalletDetailsCard.js
=> CN-8363: borrow like billionaire

app/components/modals/InterestReminderModal/InterestReminderModal.js
=> CN-8270 Crushes Got Crushed

app/components/modals/GetCoinsConfirmModal/GetCoinsConfirmModal.js, app/components/modals/GetCoinsEnterAmountInfoModal/GetCoinsEnterAmountInfoModal.js, app/components/modals/GetCoinsInfoModal/GetCoinsInfoModal.js
=> CN-8516: updated fee wordings in simplex flow

app/components/screens/LoanTermsOfUse/LoanTermsOfUse.js, app/redux/loans/loansActions.js, app/services/loans-service.js
=> CN-7575 Removed verification for loan application

android/app/build.gradle, app/components/atoms/PaymentListItem/PaymentListItem.js, app/components/organisms/LoanOverviewCard/LoanOverviewCard.js, app/components/screens/BorrowLanding/BorrowLanding.js, app/components/screens/ConfirmExtendLoan/ConfirmExtendLoan.js, app/components/screens/ExtendLoanScreen/ExtendLoanScreen.js
=> CN-8486 loan bugs

app/components/molecules/DeepLinkController/DeepLinkController.js, app/redux/app/appActions.js, app/utils/deepLink-util.js
=> CN-8751: DeepLink modifications

app/components/screens/ConfirmExtendLoan/ConfirmExtendLoan.js, app/components/screens/ExtendLoanScreen/ExtendLoanScreen.js, app/components/screens/ExtendLoanScreen/ExtendLoanScreen.styles.js
=> CN-8662 Change additional numbers from crypto to usd calculation

app/App.js, app/components/modals/CelPayReceivedModal/CelPayReceivedModal.js, app/components/screens/KYCCheckPhotos/KYCCheckPhotos.js, app/components/screens/KYCCheckPhotos/KYCCheckPhotos.styles.js, app/components/screens/TransactionsIntersection/TransactionsIntersection.js, app/components/screens/WalletLanding/WalletLanding.js, app/redux/transactions/transactionsActions.js, app/services/transactions-service.js
=> CN-8574, CN-8369, CN-8287: bug fixing KYC, CelPay, transactions

app/components/modals/InterestReminderModal/InterestReminderModal.js, app/utils/loanPayment-util.js
=> CN-8627  User sees wrong amount on reminder modal
